export const VERSION='9.4.0';
const C=()=>({'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type,accept,mcp-session-id,mcp-protocol-version,last-event-id,authorization','cache-control':'no-store','vary':'Origin, Accept'});
export const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C(),'content-type':'application/json;charset=utf-8'}});
const ts=()=>new Date().toISOString();
async function rb(r){try{return await r.json()}catch{return{}}}
async function rebuild(DB){await DB.prepare('DELETE FROM exercise_state').run();await DB.prepare(`INSERT INTO exercise_state(exercise_id,last_weight_lb,last_reps,last_seconds,last_rir,best_weight_lb,best_reps,best_seconds,next_weight_lb,next_reps_target,updated_at) SELECT l.exercise_id,l.weight_lb,l.reps,l.seconds,l.rir,b.bw,b.br,b.bs,l.weight_lb,l.reps,? FROM set_logs l JOIN (SELECT exercise_id,MAX(id) mid,MAX(weight_lb) bw,MAX(reps) br,MAX(seconds) bs FROM set_logs GROUP BY exercise_id)b ON b.exercise_id=l.exercise_id AND b.mid=l.id`).bind(ts()).run()}
async function hist(DB){const ss=(await DB.prepare(`SELECT w.*,COUNT(s.id) sets,COALESCE(SUM(COALESCE(s.weight_lb,0)*COALESCE(s.reps,0)),0) volume_lb_reps FROM workout_sessions w LEFT JOIN set_logs s ON s.session_id=w.id GROUP BY w.id ORDER BY w.started_at DESC LIMIT 500`).all()).results||[],ls=(await DB.prepare('SELECT * FROM set_logs ORDER BY completed_at DESC,id DESC LIMIT 10000').all()).results||[],m=new Map();for(const l of ls){if(!m.has(l.session_id))m.set(l.session_id,[]);m.get(l.session_id).push(l)}const sessions=ss.map(s=>({...s,set_logs:(m.get(s.id)||[]).sort((a,b)=>(a.set_number||0)-(b.set_number||0))}));return{type:'managed-history',version:VERSION,summary:{sessions:sessions.length,sets:sessions.reduce((a,s)=>a+(+s.sets||0),0),volume_lb_reps:sessions.reduce((a,s)=>a+(+s.volume_lb_reps||0),0),minutes:Math.round(sessions.reduce((a,s)=>a+(+s.duration_seconds||0),0)/60)},sessions}}
const uid=()=>crypto.randomUUID();
async function act(DB,a){const z=a.action,x=a.fields||{};
 if(z==='add-session'){const id=a.session_id||uid(),date=x.workout_date||new Date().toISOString().slice(0,10),day=x.day_name||new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'long',timeZone:'UTC'}),started=x.started_at||ts();await DB.prepare(`INSERT INTO workout_sessions(id,workout_date,day_name,started_at,completed_at,duration_seconds,status,session_rpe,notes) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,date,day,started,x.completed_at??null,x.duration_seconds??null,x.status||'complete',x.session_rpe??null,x.notes??null).run();const session=await DB.prepare('SELECT * FROM workout_sessions WHERE id=?').bind(id).first();return{ok:true,action:z,session}}
 if(z==='duplicate-session'){const src=await DB.prepare('SELECT * FROM workout_sessions WHERE id=?').bind(a.session_id).first();if(!src)throw Error('Workout session not found');const id=uid(),date=x.workout_date||new Date().toISOString().slice(0,10),day=x.day_name||src.day_name;await DB.prepare(`INSERT INTO workout_sessions(id,workout_date,day_name,started_at,completed_at,duration_seconds,status,session_rpe,notes) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,date,day,ts(),ts(),src.duration_seconds,'complete',src.session_rpe,(src.notes?src.notes+' · ':'')+'Duplicated from '+src.workout_date).run();const sets=(await DB.prepare('SELECT * FROM set_logs WHERE session_id=? ORDER BY set_number,id').bind(a.session_id).all()).results||[];for(const l of sets)await DB.prepare(`INSERT INTO set_logs(session_id,exercise_id,set_number,weight_lb,reps,seconds,rir,rpe,discomfort,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,l.exercise_id,l.set_number,l.weight_lb,l.reps,l.seconds,l.rir,l.rpe,l.discomfort,ts()).run();await rebuild(DB);return{ok:true,action:z,session_id:id,sets:sets.length}}
 if(z==='add-set'){if(!a.session_id)throw Error('session_id is required');if(!x.exercise_id)throw Error('Exercise is required');const s=await DB.prepare('SELECT id FROM workout_sessions WHERE id=?').bind(a.session_id).first();if(!s)throw Error('Workout session not found');const max=await DB.prepare('SELECT MAX(set_number) n FROM set_logs WHERE session_id=? AND exercise_id=?').bind(a.session_id,x.exercise_id).first();const setn=x.set_number??((+max?.n||0)+1);await DB.prepare(`INSERT INTO set_logs(session_id,exercise_id,set_number,weight_lb,reps,seconds,rir,rpe,discomfort,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(a.session_id,x.exercise_id,setn,x.weight_lb??null,x.reps??null,x.seconds??null,x.rir??null,x.rpe??null,x.discomfort??null,x.completed_at||ts()).run();const set=await DB.prepare('SELECT * FROM set_logs WHERE session_id=? ORDER BY id DESC LIMIT 1').bind(a.session_id).first();await rebuild(DB);return{ok:true,action:z,set}}
 if(z==='delete-session'){await DB.batch([DB.prepare('DELETE FROM set_logs WHERE session_id=?').bind(a.session_id),DB.prepare('DELETE FROM workout_sessions WHERE id=?').bind(a.session_id)]);await rebuild(DB);return{ok:true,action:z,deleted_session_id:a.session_id}}
 if(z==='update-session'){await DB.prepare(`UPDATE workout_sessions SET workout_date=COALESCE(?,workout_date),day_name=COALESCE(?,day_name),duration_seconds=?,session_rpe=?,notes=?,status=COALESCE(?,status) WHERE id=?`).bind(x.workout_date??null,x.day_name??null,x.duration_seconds??null,x.session_rpe??null,x.notes??null,x.status??null,a.session_id).run();const session=await DB.prepare('SELECT * FROM workout_sessions WHERE id=?').bind(a.session_id).first();if(!session)throw Error('Workout session not found');return{ok:true,action:z,session}}
 if(z==='update-set'){if(a.id==null)throw Error('Set id is required');await DB.prepare('UPDATE set_logs SET exercise_id=COALESCE(?,exercise_id),set_number=?,weight_lb=?,reps=?,seconds=?,rir=?,rpe=?,discomfort=? WHERE id=?').bind(x.exercise_id??null,x.set_number??1,x.weight_lb??null,x.reps??null,x.seconds??null,x.rir??null,x.rpe??null,x.discomfort??null,a.id).run();const set=await DB.prepare('SELECT * FROM set_logs WHERE id=?').bind(a.id).first();if(!set)throw Error('Workout set not found');await rebuild(DB);return{ok:true,action:z,set}}
 if(z==='delete-set'){await DB.prepare('DELETE FROM set_logs WHERE id=?').bind(a.id).run();await rebuild(DB);return{ok:true,action:z,deleted_set_id:a.id}}
 if(z==='stop-current'){const s=await DB.prepare("SELECT id FROM workout_sessions WHERE status='active' ORDER BY started_at DESC LIMIT 1").first();if(s)await DB.prepare("UPDATE workout_sessions SET status='abandoned',completed_at=COALESCE(completed_at,?) WHERE id=?").bind(ts(),s.id).run();return{ok:true,action:z,session_id:s?.id||null}}
 if(z==='reset-current'){const s=await DB.prepare("SELECT id FROM workout_sessions WHERE status='active' ORDER BY started_at DESC LIMIT 1").first();if(s){await DB.batch([DB.prepare('DELETE FROM set_logs WHERE session_id=?').bind(s.id),DB.prepare('DELETE FROM workout_sessions WHERE id=?').bind(s.id)]);await rebuild(DB)}return{ok:true,action:z,session_id:s?.id||null}}
 if(z==='reset-history'){if(a.confirm!=='RESET')throw Error('Reset history requires confirm=RESET');await DB.batch([DB.prepare('DELETE FROM set_logs'),DB.prepare('DELETE FROM workout_sessions'),DB.prepare('DELETE FROM exercise_state')]);return{ok:true,action:z}}
 if(z==='reset-customizations'){if(a.confirm!=='RESET')throw Error('Reset customizations requires confirm=RESET');await DB.batch([DB.prepare('DELETE FROM exercise_overrides'),DB.prepare('DELETE FROM video_overrides')]);return{ok:true,action:z}}
 if(z==='reset-preview'){const h=await DB.prepare('SELECT COUNT(*) n FROM workout_sessions').first(),o=await DB.prepare('SELECT COUNT(*) n FROM exercise_overrides').first(),v=await DB.prepare('SELECT COUNT(*) n FROM video_overrides').first();return{ok:true,action:z,history_sessions:+(h?.n||0),exercise_overrides:+(o?.n||0),video_overrides:+(v?.n||0)}}
 throw Error('Unknown management action')}
function safe(s){return String(s??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,' ').replace(/[()\\]/g,m=>'\\'+m).replace(/\s+/g,' ').trim()}
function pdfBytes(lines,title='DBACK Fitness - Workout History'){
 const chunks=[];for(let i=0;i<lines.length;i+=43)chunks.push(lines.slice(i,i+43));if(!chunks.length)chunks.push(['No workout history records.']);
 const objs=[null];const add=s=>{objs.push(s);return objs.length-1};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');const pages=[];
 for(let p=0;p<chunks.length;p++){let y=754,stream=`BT /F2 15 Tf 44 ${y} Td (${safe(title)}) Tj ET\n`;y-=25;stream+=`BT /F1 8 Tf 44 ${y} Td (Generated ${safe(new Date().toLocaleString())} - Page ${p+1} of ${chunks.length}) Tj ET\n`;y-=22;for(const line of chunks[p]){stream+=`BT /F1 8 Tf 44 ${y} Td (${safe(line).slice(0,115)}) Tj ET\n`;y-=15}const content=add(`<< /Length ${new TextEncoder().encode(stream).length} >>\nstream\n${stream}endstream`);const page=add(`__PAGE__`);pages.push({page,content})}
 const kids=pages.map(x=>`${x.page} 0 R`).join(' '),pagesObj=add(`<< /Type /Pages /Kids [${kids}] /Count ${pages.length} >>`);for(const x of pages)objs[x.page]=`<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${x.content} 0 R >>`;const catalog=add(`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`);
 let out='%PDF-1.4\n',offsets=[0];for(let i=1;i<objs.length;i++){offsets[i]=new TextEncoder().encode(out).length;out+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=new TextEncoder().encode(out).length;out+=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)out+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${objs.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(out)}
async function pdf(DB,sessionId){const h=await hist(DB),sessions=sessionId?h.sessions.filter(s=>s.id===sessionId):h.sessions;if(sessionId&&!sessions.length)throw Error('Workout session not found');const lines=[];lines.push(`Summary: ${sessions.length} workouts | ${sessions.reduce((a,s)=>a+(+s.sets||0),0)} sets | ${Math.round(sessions.reduce((a,s)=>a+(+s.duration_seconds||0),0)/60)} minutes`);for(const s of sessions){lines.push('');lines.push(`${s.workout_date} | ${s.day_name} | ${s.status} | ${s.duration_seconds||0}s | RPE ${s.session_rpe??'-'} | ${s.sets||0} sets`);if(s.notes)lines.push(`Notes: ${s.notes}`);for(const l of s.set_logs)lines.push(`  ${l.exercise_id} | Set ${l.set_number??'-'} | ${l.weight_lb??'-'} lb | ${l.reps??'-'} reps | ${l.seconds??'-'} sec | RIR ${l.rir??'-'} | RPE ${l.rpe??'-'}`)}const bytes=pdfBytes(lines,sessionId?'DBACK Fitness - Workout Report':'DBACK Fitness - Workout History');return new Response(bytes,{headers:{...C(),'content-type':'application/pdf','content-disposition':`attachment; filename="${sessionId?'dback-workout-report':'dback-workout-history'}.pdf"`}})}
async function exp(DB,f,sessionId){if(f==='pdf')return pdf(DB,sessionId);const h=await hist(DB),sessions=sessionId?h.sessions.filter(s=>s.id===sessionId):h.sessions;if(f!=='csv')return new Response(JSON.stringify({...h,sessions},null,2),{headers:{...C(),'content-type':'application/json','content-disposition':'attachment; filename="dback-workout-history.json"'}});const q=v=>'"'+String(v??'').replaceAll('"','""')+'"',r=[['session_id','date','day','status','duration_sec','session_rpe','notes','set_id','exercise_id','set_number','weight_lb','reps','seconds','rir','rpe','discomfort']];for(const s of sessions){if(!s.set_logs.length)r.push([s.id,s.workout_date,s.day_name,s.status,s.duration_seconds,s.session_rpe,s.notes,'','','','','','','','','']);for(const l of s.set_logs)r.push([s.id,s.workout_date,s.day_name,s.status,s.duration_seconds,s.session_rpe,s.notes,l.id,l.exercise_id,l.set_number,l.weight_lb,l.reps,l.seconds,l.rir,l.rpe,l.discomfort])}return new Response(r.map(x=>x.map(q).join(',')).join('\n'),{headers:{...C(),'content-type':'text/csv','content-disposition':'attachment; filename="dback-workout-history.csv"'}})}
async function cleanQA(DB,ids){for(const id of ids){await DB.prepare('DELETE FROM set_logs WHERE session_id=?').bind(id).run();await DB.prepare('DELETE FROM workout_sessions WHERE id=?').bind(id).run()}await DB.prepare("DELETE FROM exercise_state WHERE exercise_id LIKE '__qa_v9_%'").run()}
export async function handleManageHistory(req,env,u){if(u.pathname==='/api/manage/history'&&req.method==='GET')return json(await hist(env.DB));if(u.pathname==='/api/manage/history'&&req.method==='POST')return json(await act(env.DB,await rb(req)));if(u.pathname==='/api/manage/history/export'&&req.method==='GET')return exp(env.DB,u.searchParams.get('format')||'json',u.searchParams.get('session_id')||null);return null}
export const cors=C;
