export const VERSION='9.0.0';
const C=()=>({'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type,accept,mcp-session-id,mcp-protocol-version,last-event-id,authorization','cache-control':'no-store','vary':'Origin, Accept'});
export const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C(),'content-type':'application/json;charset=utf-8'}});
const ts=()=>new Date().toISOString();
async function rb(r){try{return await r.json()}catch{return{}}}
async function rebuild(DB){await DB.prepare('DELETE FROM exercise_state').run();await DB.prepare(`INSERT INTO exercise_state(exercise_id,last_weight_lb,last_reps,last_seconds,last_rir,best_weight_lb,best_reps,best_seconds,next_weight_lb,next_reps_target,updated_at) SELECT l.exercise_id,l.weight_lb,l.reps,l.seconds,l.rir,b.bw,b.br,b.bs,l.weight_lb,l.reps,? FROM set_logs l JOIN (SELECT exercise_id,MAX(id) mid,MAX(weight_lb) bw,MAX(reps) br,MAX(seconds) bs FROM set_logs GROUP BY exercise_id)b ON b.exercise_id=l.exercise_id AND b.mid=l.id`).bind(ts()).run()}
async function hist(DB){const ss=(await DB.prepare(`SELECT w.*,COUNT(s.id) sets,COALESCE(SUM(COALESCE(s.weight_lb,0)*COALESCE(s.reps,0)),0) volume_lb_reps FROM workout_sessions w LEFT JOIN set_logs s ON s.session_id=w.id GROUP BY w.id ORDER BY w.started_at DESC LIMIT 250`).all()).results||[],ls=(await DB.prepare('SELECT * FROM set_logs ORDER BY completed_at DESC,id DESC LIMIT 5000').all()).results||[],m=new Map();for(const l of ls){if(!m.has(l.session_id))m.set(l.session_id,[]);m.get(l.session_id).push(l)}return{type:'managed-history',version:VERSION,sessions:ss.map(s=>({...s,set_logs:m.get(s.id)||[]}))}}
async function act(DB,a){const z=a.action,x=a.fields||{};if(z==='delete-session'){await DB.batch([DB.prepare('DELETE FROM set_logs WHERE session_id=?').bind(a.session_id),DB.prepare('DELETE FROM workout_sessions WHERE id=?').bind(a.session_id)]);await rebuild(DB)}else if(z==='update-session'){await DB.prepare(`UPDATE workout_sessions SET workout_date=COALESCE(?,workout_date),day_name=COALESCE(?,day_name),duration_seconds=?,session_rpe=?,notes=?,status=COALESCE(?,status) WHERE id=?`).bind(x.workout_date??null,x.day_name??null,x.duration_seconds??null,x.session_rpe??null,x.notes??null,x.status??null,a.session_id).run()}else if(z==='update-set'){await DB.prepare('UPDATE set_logs SET set_number=?,weight_lb=?,reps=?,seconds=?,rir=? WHERE id=?').bind(x.set_number??1,x.weight_lb??null,x.reps??null,x.seconds??null,x.rir??null,a.id).run();await rebuild(DB)}else if(z==='delete-set'){await DB.prepare('DELETE FROM set_logs WHERE id=?').bind(a.id).run();await rebuild(DB)}else if(z==='stop-current'){const s=await DB.prepare("SELECT id FROM workout_sessions WHERE status='active' ORDER BY started_at DESC LIMIT 1").first();if(s)await DB.prepare("UPDATE workout_sessions SET status='abandoned',completed_at=COALESCE(completed_at,?) WHERE id=?").bind(ts(),s.id).run()}else if(z==='reset-current'){const s=await DB.prepare("SELECT id FROM workout_sessions WHERE status='active' ORDER BY started_at DESC LIMIT 1").first();if(s){await DB.batch([DB.prepare('DELETE FROM set_logs WHERE session_id=?').bind(s.id),DB.prepare('DELETE FROM workout_sessions WHERE id=?').bind(s.id)]);await rebuild(DB)}}else if(z==='reset-history'){await DB.batch([DB.prepare('DELETE FROM set_logs'),DB.prepare('DELETE FROM workout_sessions'),DB.prepare('DELETE FROM exercise_state')])}else if(z==='reset-customizations'){await DB.batch([DB.prepare('DELETE FROM exercise_overrides'),DB.prepare('DELETE FROM video_overrides')])}else throw Error('Unknown management action');return{ok:true,action:z}}
async function exp(DB,f){const h=await hist(DB);if(f!=='csv')return new Response(JSON.stringify(h,null,2),{headers:{...C(),'content-type':'application/json','content-disposition':'attachment; filename="dback-workout-history.json"'}});const q=v=>'"'+String(v??'').replaceAll('"','""')+'"',r=[['session_id','date','day','status','duration_sec','session_rpe','notes','set_id','exercise_id','set_number','weight_lb','reps','seconds','rir']];for(const s of h.sessions){if(!s.set_logs.length)r.push([s.id,s.workout_date,s.day_name,s.status,s.duration_seconds,s.session_rpe,s.notes,'','','','','','','']);for(const l of s.set_logs)r.push([s.id,s.workout_date,s.day_name,s.status,s.duration_seconds,s.session_rpe,s.notes,l.id,l.exercise_id,l.set_number,l.weight_lb,l.reps,l.seconds,l.rir])}return new Response(r.map(x=>x.map(q).join(',')).join('\n'),{headers:{...C(),'content-type':'text/csv','content-disposition':'attachment; filename="dback-workout-history.csv"'}})}
export async function handleManageHistory(req,env,u){if(u.pathname==='/api/manage/history'&&req.method==='GET')return json(await hist(env.DB));if(u.pathname==='/api/manage/history'&&req.method==='POST')return json(await act(env.DB,await rb(req)));if(u.pathname==='/api/manage/history/export'&&req.method==='GET')return exp(env.DB,u.searchParams.get('format')||'json');return null}
export const cors=C;
