import base from './worker-v5.js';

const VERSION='6.0.0';
const SCIENCE_REFERENCES=[
 {title:'OpenStax Anatomy & Physiology 2e — Muscular System',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-introduction',type:'anatomy'},
 {title:'OpenStax — Skeletal muscle interactions and lever systems',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-1-interactions-of-skeletal-muscles-their-fascicle-arrangement-and-their-lever-systems',type:'biomechanics'},
 {title:'ACSM — Resistance Training Prescription for Muscle Function, Hypertrophy, and Physical Performance',url:'https://acsm.org/resistance-training-guidelines-update-2026/',type:'training'},
 {title:'PubMed — Single- and Multi-Joint Exercise Review',url:'https://pubmed.ncbi.nlm.nih.gov/27677913/',type:'exercise-selection'}
];

const MUSCLES=[
 {id:'neck-flexors',name:'Cervical Flexors',region:'Neck',view:'front',parts:['Sternocleidomastoid','Scalenes','Longus colli'],actions:['cervical flexion','rotation','lateral flexion'],joints:['cervical-spine']},
 {id:'upper-trapezius',name:'Upper Trapezius',region:'Upper Back',view:'back',parts:['Upper trapezius'],actions:['scapular elevation','upward rotation'],joints:['scapulothoracic','shoulder']},
 {id:'mid-trapezius',name:'Middle Trapezius',region:'Upper Back',view:'back',parts:['Middle trapezius'],actions:['scapular retraction'],joints:['scapulothoracic']},
 {id:'lower-trapezius',name:'Lower Trapezius',region:'Upper Back',view:'back',parts:['Lower trapezius'],actions:['scapular depression','upward rotation'],joints:['scapulothoracic']},
 {id:'rhomboids',name:'Rhomboids',region:'Upper Back',view:'back',parts:['Rhomboid major','Rhomboid minor'],actions:['scapular retraction','downward rotation'],joints:['scapulothoracic']},
 {id:'anterior-deltoid',name:'Anterior Deltoid',region:'Shoulder',view:'front',parts:['Anterior deltoid'],actions:['shoulder flexion','horizontal adduction'],joints:['shoulder']},
 {id:'lateral-deltoid',name:'Lateral Deltoid',region:'Shoulder',view:'both',parts:['Middle deltoid'],actions:['shoulder abduction'],joints:['shoulder']},
 {id:'posterior-deltoid',name:'Posterior Deltoid',region:'Shoulder',view:'back',parts:['Posterior deltoid'],actions:['shoulder extension','horizontal abduction'],joints:['shoulder']},
 {id:'rotator-cuff',name:'Rotator Cuff',region:'Shoulder',view:'back',parts:['Supraspinatus','Infraspinatus','Teres minor','Subscapularis'],actions:['glenohumeral stabilization','internal/external rotation','abduction assistance'],joints:['shoulder']},
 {id:'pectoralis-major',name:'Pectoralis Major',region:'Chest',view:'front',parts:['Clavicular head','Sternocostal head'],actions:['horizontal adduction','shoulder flexion','internal rotation'],joints:['shoulder']},
 {id:'pectoralis-minor',name:'Pectoralis Minor',region:'Chest',view:'front',parts:['Pectoralis minor'],actions:['scapular protraction','anterior tilt'],joints:['scapulothoracic']},
 {id:'serratus-anterior',name:'Serratus Anterior',region:'Chest',view:'front',parts:['Serratus anterior'],actions:['scapular protraction','upward rotation'],joints:['scapulothoracic']},
 {id:'latissimus-dorsi',name:'Latissimus Dorsi',region:'Back',view:'back',parts:['Latissimus dorsi'],actions:['shoulder extension','adduction','internal rotation'],joints:['shoulder']},
 {id:'teres-major',name:'Teres Major',region:'Back',view:'back',parts:['Teres major'],actions:['shoulder extension','adduction','internal rotation'],joints:['shoulder']},
 {id:'biceps-brachii',name:'Biceps Brachii',region:'Upper Arm',view:'front',parts:['Long head biceps','Short head biceps'],actions:['elbow flexion','forearm supination','shoulder flexion assistance'],joints:['elbow','radioulnar','shoulder']},
 {id:'brachialis',name:'Brachialis',region:'Upper Arm',view:'front',parts:['Brachialis'],actions:['elbow flexion'],joints:['elbow']},
 {id:'triceps-brachii',name:'Triceps Brachii',region:'Upper Arm',view:'back',parts:['Long head triceps','Lateral head triceps','Medial head triceps'],actions:['elbow extension','shoulder extension assistance'],joints:['elbow','shoulder']},
 {id:'forearm-flexors',name:'Forearm Flexors',region:'Forearm',view:'front',parts:['Flexor carpi radialis','Flexor carpi ulnaris','Palmaris longus','Finger flexors','Pronator teres'],actions:['wrist flexion','finger flexion','pronation'],joints:['wrist','radioulnar']},
 {id:'forearm-extensors',name:'Forearm Extensors',region:'Forearm',view:'back',parts:['Extensor carpi radialis','Extensor carpi ulnaris','Finger extensors','Supinator'],actions:['wrist extension','finger extension','supination assistance'],joints:['wrist','radioulnar']},
 {id:'rectus-abdominis',name:'Rectus Abdominis',region:'Core',view:'front',parts:['Rectus abdominis'],actions:['trunk flexion','pelvic control','anti-extension'],joints:['lumbar-spine']},
 {id:'obliques',name:'Obliques',region:'Core',view:'front',parts:['External oblique','Internal oblique'],actions:['trunk rotation','lateral flexion','anti-rotation'],joints:['thoracic-spine','lumbar-spine']},
 {id:'transverse-abdominis',name:'Transverse Abdominis',region:'Core',view:'front',parts:['Transversus abdominis'],actions:['abdominal bracing','trunk stabilization'],joints:['lumbar-spine']},
 {id:'erector-spinae',name:'Erector Spinae',region:'Back',view:'back',parts:['Iliocostalis','Longissimus','Spinalis'],actions:['spinal extension','anti-flexion'],joints:['thoracic-spine','lumbar-spine']},
 {id:'multifidus',name:'Multifidus',region:'Back',view:'back',parts:['Multifidus'],actions:['segmental spinal stabilization','rotation control'],joints:['thoracic-spine','lumbar-spine']},
 {id:'quadratus-lumborum',name:'Quadratus Lumborum',region:'Low Back',view:'back',parts:['Quadratus lumborum'],actions:['lateral flexion','pelvic stabilization'],joints:['lumbar-spine','sacroiliac']},
 {id:'hip-flexors',name:'Hip Flexors',region:'Hip',view:'front',parts:['Iliacus','Psoas major','Rectus femoris','Sartorius'],actions:['hip flexion'],joints:['hip']},
 {id:'gluteus-maximus',name:'Gluteus Maximus',region:'Glutes',view:'back',parts:['Gluteus maximus'],actions:['hip extension','external rotation'],joints:['hip']},
 {id:'gluteus-medius',name:'Gluteus Medius / Minimus',region:'Glutes',view:'back',parts:['Gluteus medius','Gluteus minimus','Tensor fasciae latae'],actions:['hip abduction','pelvic stabilization','internal/external rotation by fiber'],joints:['hip']},
 {id:'adductors',name:'Hip Adductors',region:'Inner Thigh',view:'front',parts:['Adductor magnus','Adductor longus','Adductor brevis','Gracilis','Pectineus'],actions:['hip adduction','hip extension/flexion assistance by region'],joints:['hip']},
 {id:'quadriceps',name:'Quadriceps',region:'Front Thigh',view:'front',parts:['Rectus femoris','Vastus lateralis','Vastus medialis','Vastus intermedius'],actions:['knee extension','hip flexion by rectus femoris'],joints:['knee','hip']},
 {id:'hamstrings',name:'Hamstrings',region:'Back Thigh',view:'back',parts:['Biceps femoris','Semitendinosus','Semimembranosus'],actions:['knee flexion','hip extension'],joints:['knee','hip']},
 {id:'gastrocnemius',name:'Gastrocnemius',region:'Calf',view:'back',parts:['Medial gastrocnemius','Lateral gastrocnemius'],actions:['plantarflexion','knee flexion assistance'],joints:['ankle','knee']},
 {id:'soleus',name:'Soleus',region:'Calf',view:'back',parts:['Soleus'],actions:['plantarflexion','postural control'],joints:['ankle']},
 {id:'tibialis-anterior',name:'Tibialis Anterior',region:'Shin',view:'front',parts:['Tibialis anterior'],actions:['dorsiflexion','inversion'],joints:['ankle','subtalar']},
 {id:'peroneals',name:'Fibularis / Peroneal Group',region:'Lower Leg',view:'both',parts:['Fibularis longus','Fibularis brevis'],actions:['eversion','plantarflexion assistance'],joints:['ankle','subtalar']},
 {id:'foot-intrinsics',name:'Intrinsic Foot Muscles',region:'Foot',view:'front',parts:['Abductor hallucis','Flexor digitorum brevis','Interossei','Lumbricals and intrinsic stabilizers'],actions:['toe control','arch support','foot stabilization'],joints:['ankle','subtalar','mtp']}
];

const JOINTS=[
 {id:'cervical-spine',name:'Cervical Spine',region:'Neck',motions:['flexion','extension','rotation','lateral flexion']},
 {id:'shoulder',name:'Glenohumeral Shoulder',region:'Shoulder',motions:['flexion','extension','abduction','adduction','internal/external rotation']},
 {id:'scapulothoracic',name:'Scapulothoracic Complex',region:'Shoulder Girdle',motions:['elevation/depression','protraction/retraction','upward/downward rotation']},
 {id:'elbow',name:'Elbow',region:'Arm',motions:['flexion','extension']},
 {id:'radioulnar',name:'Radioulnar Complex',region:'Forearm',motions:['pronation','supination']},
 {id:'wrist',name:'Wrist',region:'Forearm',motions:['flexion','extension','radial/ulnar deviation']},
 {id:'thoracic-spine',name:'Thoracic Spine',region:'Spine',motions:['rotation','extension','flexion','lateral flexion']},
 {id:'lumbar-spine',name:'Lumbar Spine',region:'Spine',motions:['flexion','extension','lateral flexion','rotation control']},
 {id:'sacroiliac',name:'Sacroiliac Region',region:'Pelvis',motions:['load transfer','small nutation/counternutation']},
 {id:'hip',name:'Hip',region:'Pelvis',motions:['flexion','extension','abduction','adduction','internal/external rotation']},
 {id:'knee',name:'Knee',region:'Leg',motions:['flexion','extension','small axial rotation']},
 {id:'ankle',name:'Talocrural Ankle',region:'Lower Leg',motions:['dorsiflexion','plantarflexion']},
 {id:'subtalar',name:'Subtalar Joint',region:'Foot',motions:['inversion','eversion']},
 {id:'mtp',name:'Metatarsophalangeal Joints',region:'Foot',motions:['toe flexion','extension']}
];

const MAPS={
 front:{
  muscles:[['neck-flexors',100,37,10,13],['anterior-deltoid',75,71,15,11],['anterior-deltoid',125,71,15,11],['lateral-deltoid',68,76,9,14],['lateral-deltoid',132,76,9,14],['pectoralis-major',85,91,18,14],['pectoralis-major',115,91,18,14],['serratus-anterior',72,112,8,19],['serratus-anterior',128,112,8,19],['biceps-brachii',55,112,8,22],['biceps-brachii',145,112,8,22],['forearm-flexors',43,151,7,25],['forearm-flexors',157,151,7,25],['rectus-abdominis',100,135,14,33],['obliques',79,139,10,30],['obliques',121,139,10,30],['hip-flexors',88,178,10,14],['hip-flexors',112,178,10,14],['adductors',91,216,9,30],['adductors',109,216,9,30],['quadriceps',75,220,13,42],['quadriceps',125,220,13,42],['tibialis-anterior',74,292,8,35],['tibialis-anterior',126,292,8,35],['peroneals',64,294,5,34],['peroneals',136,294,5,34],['foot-intrinsics',72,344,13,7],['foot-intrinsics',128,344,13,7]],
  joints:[['cervical-spine',100,48],['shoulder',72,76],['shoulder',128,76],['elbow',49,132],['elbow',151,132],['wrist',39,176],['wrist',161,176],['hip',86,184],['hip',114,184],['knee',74,260],['knee',126,260],['ankle',72,329],['ankle',128,329]]
 },
 back:{
  muscles:[['upper-trapezius',100,68,27,18],['mid-trapezius',100,92,24,15],['lower-trapezius',100,112,18,23],['rhomboids',100,94,15,19],['posterior-deltoid',70,80,13,12],['posterior-deltoid',130,80,13,12],['rotator-cuff',78,91,10,12],['rotator-cuff',122,91,10,12],['triceps-brachii',55,116,8,24],['triceps-brachii',145,116,8,24],['forearm-extensors',43,153,7,26],['forearm-extensors',157,153,7,26],['latissimus-dorsi',80,125,17,35],['latissimus-dorsi',120,125,17,35],['erector-spinae',90,145,8,40],['erector-spinae',110,145,8,40],['quadratus-lumborum',82,159,8,18],['quadratus-lumborum',118,159,8,18],['gluteus-medius',79,190,12,14],['gluteus-medius',121,190,12,14],['gluteus-maximus',83,208,18,24],['gluteus-maximus',117,208,18,24],['hamstrings',76,252,13,40],['hamstrings',124,252,13,40],['gastrocnemius',73,313,11,28],['gastrocnemius',127,313,11,28],['soleus',73,325,8,22],['soleus',127,325,8,22],['peroneals',63,301,5,32],['peroneals',137,301,5,32],['foot-intrinsics',72,346,13,7],['foot-intrinsics',128,346,13,7]],
  joints:[['cervical-spine',100,48],['scapulothoracic',83,89],['scapulothoracic',117,89],['shoulder',70,78],['shoulder',130,78],['elbow',49,134],['elbow',151,134],['wrist',39,178],['wrist',161,178],['thoracic-spine',100,115],['lumbar-spine',100,160],['sacroiliac',100,185],['hip',85,198],['hip',115,198],['knee',74,272],['knee',126,272],['ankle',72,334],['ankle',128,334]]
 }
};

const uniq=a=>[...new Set((a||[]).filter(Boolean))];
const P=(primary=[],secondary=[],stabilizers=[],joints=[],pattern='general',plane='multi-planar',mechanic='compound',actions=[],chain='mixed')=>({primary:uniq(primary),secondary:uniq(secondary),stabilizers:uniq(stabilizers),joints:uniq(joints),pattern,plane,mechanic,actions:uniq(actions),chain,compoundScore:mechanic==='compound'?Math.min(10,5+uniq(primary.concat(secondary)).length):2});
function exerciseProfile(name){
 const n=String(name||'').toLowerCase();
 if(/thruster|squat.to.press/.test(n))return P(['quadriceps','gluteus-maximus','anterior-deltoid','triceps-brachii'],['hamstrings','lateral-deltoid','upper-trapezius'],['rectus-abdominis','obliques','erector-spinae'],['hip','knee','ankle','shoulder','elbow'],'squat + vertical press','sagittal','compound',['knee extension','hip extension','shoulder flexion','elbow extension'],'closed-to-open');
 if(/push press/.test(n))return P(['anterior-deltoid','triceps-brachii','quadriceps','gluteus-maximus'],['lateral-deltoid','upper-trapezius'],['rectus-abdominis','obliques','erector-spinae'],['hip','knee','ankle','shoulder','elbow'],'power press','sagittal','compound',['triple extension assistance','shoulder flexion','elbow extension'],'open');
 if(/front squat|goblet squat|bodyweight squat|double.dumbbell front squat|deep squat/.test(n))return P(['quadriceps','gluteus-maximus'],['adductors','hamstrings'],['gluteus-medius','rectus-abdominis','obliques','erector-spinae'],['hip','knee','ankle'],'squat','sagittal','compound',['knee extension','hip extension'],'closed');
 if(/bulgarian|split squat|reverse lunge|lateral lunge|lunge/.test(n))return P(['quadriceps','gluteus-maximus'],['hamstrings','adductors'],['gluteus-medius','obliques','foot-intrinsics'],['hip','knee','ankle'],'lunge','sagittal/frontal','compound',['knee extension','hip extension','pelvic stabilization'],'closed');
 if(/romanian deadlift|\brdl\b|deadlift|hinge/.test(n))return P(['hamstrings','gluteus-maximus'],['erector-spinae','adductors'],['latissimus-dorsi','rectus-abdominis','obliques','foot-intrinsics'],['hip','knee','lumbar-spine'],'hinge','sagittal','compound',['hip extension','anti-flexion'],'closed');
 if(/glute bridge|hip thrust/.test(n))return P(['gluteus-maximus'],['hamstrings'],['rectus-abdominis','gluteus-medius'],['hip','lumbar-spine'],'hip extension','sagittal','compound',['hip extension','pelvic stabilization'],'closed');
 if(/pull.up|chin.up|dead hang/.test(n))return P(['latissimus-dorsi','biceps-brachii'],['rhomboids','mid-trapezius','posterior-deltoid','brachialis'],['rotator-cuff','forearm-flexors','rectus-abdominis'],['shoulder','elbow','scapulothoracic'],'vertical pull','frontal/sagittal','compound',['shoulder adduction/extension','elbow flexion','scapular depression'],'open');
 if(/row/.test(n))return P(['latissimus-dorsi','rhomboids','mid-trapezius'],['biceps-brachii','posterior-deltoid','brachialis'],['rotator-cuff','erector-spinae','obliques'],['shoulder','elbow','scapulothoracic'],'horizontal pull','transverse','compound',['shoulder extension','scapular retraction','elbow flexion'],'open');
 if(/floor press|chest press/.test(n))return P(['pectoralis-major','triceps-brachii'],['anterior-deltoid'],['serratus-anterior','rotator-cuff'],['shoulder','elbow','scapulothoracic'],'horizontal press','transverse','compound',['horizontal adduction','elbow extension'],'open');
 if(/push.up plus|scapular push/.test(n))return P(['serratus-anterior','pectoralis-major'],['triceps-brachii','anterior-deltoid'],['rotator-cuff','rectus-abdominis','obliques'],['shoulder','elbow','scapulothoracic'],'horizontal press + protraction','transverse','compound',['scapular protraction','elbow extension'],'closed');
 if(/push.up/.test(n))return P(['pectoralis-major','triceps-brachii'],['anterior-deltoid','serratus-anterior'],['rotator-cuff','rectus-abdominis','obliques','gluteus-maximus'],['shoulder','elbow','scapulothoracic','lumbar-spine'],'horizontal press','transverse','compound',['horizontal adduction','elbow extension','anti-extension'],'closed');
 if(/overhead press|standing dumbbell press|kneeling.*press|dumbbell press/.test(n))return P(['anterior-deltoid','triceps-brachii'],['lateral-deltoid','upper-trapezius'],['rotator-cuff','serratus-anterior','rectus-abdominis','obliques'],['shoulder','elbow','scapulothoracic'],'vertical press','frontal/sagittal','compound',['shoulder flexion/abduction','elbow extension','upward rotation'],'open');
 if(/lateral raise/.test(n))return P(['lateral-deltoid'],['upper-trapezius','rotator-cuff'],['serratus-anterior'],['shoulder','scapulothoracic'],'shoulder abduction','frontal','isolation',['shoulder abduction'],'open');
 if(/reverse fly|floor y|floor t|y.t.w|wall slide/.test(n))return P(['posterior-deltoid','rhomboids','mid-trapezius','lower-trapezius'],['rotator-cuff'],['serratus-anterior','upper-trapezius'],['shoulder','scapulothoracic'],'scapular control','transverse/frontal','compound',['scapular retraction','upward rotation','external rotation'],'open');
 if(/hammer curl|curl/.test(n))return P(['biceps-brachii','brachialis'],['forearm-flexors'],[],['elbow','radioulnar'],'elbow flexion','sagittal','isolation',['elbow flexion'],'open');
 if(/triceps extension/.test(n))return P(['triceps-brachii'],['anterior-deltoid'],[],['elbow','shoulder'],'elbow extension','sagittal','isolation',['elbow extension'],'open');
 if(/farmer|suitcase|carry|march/.test(n))return P(['forearm-flexors','obliques','erector-spinae'],['upper-trapezius','gluteus-medius','gluteus-maximus'],['transverse-abdominis','multifidus','foot-intrinsics'],['shoulder','lumbar-spine','hip','knee','ankle'],'loaded carry','multi-planar','compound',['anti-lateral-flexion','grip','gait stabilization'],'closed');
 if(/side plank/.test(n))return P(['obliques','transverse-abdominis'],['gluteus-medius','quadratus-lumborum'],['rotator-cuff','serratus-anterior'],['shoulder','lumbar-spine','hip'],'anti-lateral-flexion','frontal','compound',['lateral trunk stabilization','pelvic stabilization'],'closed');
 if(/plank|hollow hold|dead bug/.test(n))return P(['rectus-abdominis','transverse-abdominis'],['obliques'],['multifidus','hip-flexors'],['lumbar-spine','hip'],'anti-extension','sagittal','compound',['trunk stabilization','pelvic control'],'closed');
 if(/bird dog/.test(n))return P(['multifidus','erector-spinae','gluteus-maximus'],['posterior-deltoid'],['transverse-abdominis','obliques'],['lumbar-spine','hip','shoulder'],'contralateral stability','multi-planar','compound',['spinal stabilization','hip extension','shoulder flexion'],'closed');
 if(/mountain climber|high knees/.test(n))return P(['hip-flexors','rectus-abdominis'],['quadriceps','anterior-deltoid'],['serratus-anterior','obliques'],['hip','knee','shoulder'],'locomotion/conditioning','sagittal','compound',['hip flexion','trunk stabilization'],'closed');
 if(/calf raise/.test(n))return P(['gastrocnemius','soleus'],[],['foot-intrinsics','peroneals'],['ankle','subtalar'],'plantarflexion','sagittal','isolation',['plantarflexion'],'closed');
 if(/tibialis/.test(n))return P(['tibialis-anterior'],[],['foot-intrinsics'],['ankle','subtalar'],'dorsiflexion','sagittal','isolation',['dorsiflexion'],'closed');
 if(/ankle inversion/.test(n))return P(['tibialis-anterior'],['foot-intrinsics'],[],['subtalar','ankle'],'inversion','frontal','isolation',['inversion'],'open');
 if(/ankle eversion/.test(n))return P(['peroneals'],['foot-intrinsics'],[],['subtalar','ankle'],'eversion','frontal','isolation',['eversion'],'open');
 if(/ankle|dorsiflexion/.test(n))return P(['tibialis-anterior','gastrocnemius','soleus'],['peroneals'],['foot-intrinsics'],['ankle','subtalar'],'ankle mobility','sagittal/frontal','mobility',['dorsiflexion','plantarflexion','ankle control'],'closed');
 if(/90\/90|hip car|hip circle|hip rotation/.test(n))return P(['gluteus-medius','adductors','hip-flexors'],['gluteus-maximus'],['obliques'],['hip'],'hip rotation/mobility','transverse','mobility',['hip internal/external rotation'],'closed');
 if(/thoracic rotation|cat.cow|child.s pose/.test(n))return P(['obliques','multifidus','erector-spinae'],['rectus-abdominis'],[],['thoracic-spine','lumbar-spine'],'spinal mobility','multi-planar','mobility',['thoracic rotation','spinal flexion/extension'],'closed');
 if(/shoulder car|shoulder circle/.test(n))return P(['rotator-cuff','anterior-deltoid','lateral-deltoid','posterior-deltoid'],['upper-trapezius','serratus-anterior'],[],['shoulder','scapulothoracic'],'shoulder mobility','multi-planar','mobility',['shoulder circumduction','scapular control'],'open');
 if(/neck car|chin tuck|neck isometric/.test(n))return P(['neck-flexors'],['upper-trapezius'],[],['cervical-spine'],'cervical control','multi-planar','mobility',['cervical control'],'closed');
 if(/wrist|pronation|supination|forearm/.test(n))return P(['forearm-flexors','forearm-extensors'],['biceps-brachii'],[],['wrist','radioulnar'],'forearm/wrist control','multi-planar','isolation',['wrist control','pronation/supination'],'open');
 if(/toe|foot/.test(n))return P(['foot-intrinsics'],['tibialis-anterior','peroneals'],[],['mtp','subtalar'],'foot control','multi-planar','isolation',['toe control','arch stabilization'],'closed');
 return P([],[],['transverse-abdominis'],[],'general','multi-planar','compound',[],'mixed');
}

function muscleById(id){return MUSCLES.find(x=>x.id===id)}
function jointById(id){return JOINTS.find(x=>x.id===id)}
function hydrateProfile(p){return{...p,primaryDetail:p.primary.map(muscleById).filter(Boolean),secondaryDetail:p.secondary.map(muscleById).filter(Boolean),stabilizerDetail:p.stabilizers.map(muscleById).filter(Boolean),jointDetail:p.joints.map(jointById).filter(Boolean)}}
function enrichExercise(e){return{...e,anatomy:hydrateProfile(exerciseProfile(e.name))}}
function enrichPayload(data,path){
 if(path==='/api/today'&&data){data.version=VERSION;data.warmup=(data.warmup||[]).map(enrichExercise);data.exercises=(data.exercises||[]).map(enrichExercise)}
 if(path==='/api/plan'&&data){data.version=VERSION;data.days=(data.days||[]).map(d=>({...d,exercises:(d.exercises||[]).map(enrichExercise)}))}
 if(path==='/api/library'&&data){data.exercises=(data.exercises||[]).map(enrichExercise)}
 if(path==='/health'&&data){data.version=VERSION;data.anatomy=true;data.biomechanics=true}
 return data;
}
function scoreExercise(e,muscles,joints,mode){const p=e.anatomy||hydrateProfile(exerciseProfile(e.name));let score=0,covered=[];for(const m of muscles){if(p.primary.includes(m)){score+=4;covered.push(m)}else if(p.secondary.includes(m)){score+=2.5;covered.push(m)}else if(p.stabilizers.includes(m)){score+=1;covered.push(m)}}for(const j of joints)if(p.joints.includes(j))score+=1.2;if(mode==='compound'&&p.mechanic==='compound')score+=2.5;if(mode==='isolation'&&p.mechanic==='isolation')score+=2.5;if(muscles.length>1&&uniq(covered).length>1)score+=uniq(covered).length*1.5;const pct=muscles.length?Math.round(100*uniq(covered).length/muscles.length):0;return{...e,anatomy:p,matchScore:+score.toFixed(1),selectedCoverage:uniq(covered),coveragePct:pct}}
async function baseJson(env,ctx,origin,path){const r=await base.fetch(new Request(origin+path,{headers:{accept:'application/json'}}),env,ctx);const t=await r.text();if(!r.ok)throw Error(t||('HTTP '+r.status));return JSON.parse(t)}
async function recommendations(env,ctx,origin,input={}){const muscles=uniq(input.muscles||[]).filter(x=>muscleById(x)),joints=uniq(input.joints||[]).filter(x=>jointById(x)),mode=input.mode||'any',goal=input.goal||'hypertrophy';const lib=enrichPayload(await baseJson(env,ctx,origin,'/api/library'),'/api/library');let list=(lib.exercises||[]).map(e=>scoreExercise(e,muscles,joints,mode)).filter(x=>x.matchScore>0);if(mode==='compound')list=list.filter(x=>x.anatomy.mechanic==='compound'||x.anatomy.mechanic==='mobility');if(mode==='isolation')list=list.filter(x=>x.anatomy.mechanic==='isolation');list.sort((a,b)=>b.matchScore-a.matchScore||b.anatomy.compoundScore-a.anatomy.compoundScore||a.name.localeCompare(b.name));return{type:'anatomy_recommendations',selectedMuscles:muscles.map(muscleById),selectedJoints:joints.map(jointById),mode,goal,results:list.slice(0,24),note:'Muscle roles are mechanics-informed training classifications. They are not individualized EMG measurements or medical diagnoses.',version:VERSION}}
function atlas(){return{type:'anatomy_atlas',version:VERSION,muscles:MUSCLES,joints:JOINTS,maps:MAPS,references:SCIENCE_REFERENCES,roleDefinitions:{primary:'Main intended force-producing muscle group for the movement pattern.',secondary:'Meaningful assisting muscle group.',stabilizer:'Contributes substantially to position, joint control, bracing, grip, or force transfer.'},scienceNote:'Exercise muscle emphasis varies with technique, anthropometry, range of motion, load, fatigue and individual anatomy. This atlas describes expected mechanical roles rather than claiming exact activation percentages.'}}

function jsonResponse(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*',...headers}})}
function rpc(id,result,status=200){return jsonResponse({jsonrpc:'2.0',id,result},status,{'mcp-protocol-version':'2025-06-18'})}
const ANATOMY_MCP_TOOLS=[
 {name:'get_anatomy_atlas',title:'Get anatomy atlas',description:'Use this when the user wants scientific muscle, joint, or body-region anatomy information.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},
 {name:'get_exercise_anatomy',title:'Get exercise anatomy',description:'Use this when the user asks which muscles and joints an exercise trains.',inputSchema:{type:'object',properties:{exercise_name:{type:'string'}},required:['exercise_name'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},
 {name:'recommend_exercises_for_muscles',title:'Recommend exercises for selected muscles',description:'Use this when the user selects one or more muscles or joints and wants matching exercises, especially compound movements that cover several targets.',inputSchema:{type:'object',properties:{muscles:{type:'array',items:{type:'string'}},joints:{type:'array',items:{type:'string'}},mode:{type:'string',enum:['any','compound','isolation']},goal:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}}
];
function toolOutput(data,text){return{structuredContent:data,content:[{type:'text',text:text||'DBACK anatomy result.'}]}}

function anatomyContext(message,lib){const q=String(message||'').toLowerCase();const selected=MUSCLES.filter(m=>q.includes(m.name.toLowerCase())||m.parts.some(p=>q.includes(p.toLowerCase())));const ex=(lib?.exercises||[]).find(e=>q.includes(String(e.name||'').toLowerCase()));let lines=[];if(selected.length)lines.push('Recognized anatomy targets: '+selected.map(x=>x.name).join(', ')+'.');if(ex){const p=ex.anatomy||hydrateProfile(exerciseProfile(ex.name));lines.push('Exercise mechanics for '+ex.name+': primary '+p.primaryDetail.map(x=>x.name).join(', ')+'; secondary '+p.secondaryDetail.map(x=>x.name).join(', ')+'; stabilizers '+p.stabilizerDetail.map(x=>x.name).join(', ')+'; joints '+p.jointDetail.map(x=>x.name).join(', ')+'; pattern '+p.pattern+'; plane '+p.plane+'; '+p.mechanic+'.')}if(!lines.length)return message;return '[DBACK Anatomy Intelligence context. Treat this as app data, not a medical diagnosis.]\n'+lines.join('\n')+'\nUser request: '+message}

const ANAT_CSS=`
.anatHero{background:linear-gradient(135deg,#102b44,#101a31);border:1px solid #2b4a67}.anatomyLayout{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:14px}.bodyGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.bodyPanel{background:#081525;border:1px solid #29425f;border-radius:18px;padding:10px;text-align:center}.human{width:100%;max-height:560px;min-height:440px}.bodyOutline{fill:#0d2236;stroke:#66809f;stroke-width:1.4}.muscleHotspot{fill:#1f4d70;stroke:#4f82a8;stroke-width:.8;opacity:.8;cursor:pointer;transition:.15s}.muscleHotspot:hover{fill:#2d6d9c}.muscleHotspot.selected{fill:#ef4444;stroke:#fecaca;opacity:.95}.jointHotspot{fill:#f59e0b;stroke:#fff3;stroke-width:1.2;cursor:pointer}.jointHotspot.selected{fill:#22c55e;stroke:#dcfce7}.anatChips{display:flex;gap:6px;flex-wrap:wrap}.anatChip{border:1px solid #355271;background:#10233a;color:#cbd5e1;border-radius:999px;padding:6px 9px;font-size:12px;cursor:pointer}.anatChip.selected{background:#7f1d1d;border-color:#ef4444;color:#fff}.anatJoint.selected{background:#14532d;border-color:#22c55e}.anatTag{display:inline-block;border:1px solid #314b68;border-radius:999px;padding:3px 7px;margin:3px 4px 0 0;font-size:11px;color:#bfdbfe;background:#0b1d31}.anatTag.primary{border-color:#dc2626;color:#fecaca;background:#351116}.anatTag.secondary{border-color:#d97706;color:#fde68a;background:#2c1a07}.anatTag.stabilizer{border-color:#2563eb;color:#bfdbfe;background:#0b1d31}.anatResult{border-top:1px solid #243653;padding:13px 0}.anatResult:first-child{border-top:0}.score{font-size:12px;font-weight:900;color:#86efac}.scienceBox{border-left:3px solid #3b82f6;padding:10px 12px;background:#0a1728;border-radius:0 12px 12px 0}.structureList{max-height:320px;overflow:auto}.structureRow{padding:8px 0;border-top:1px solid #20334d}.structureRow:first-child{border-top:0}.anatomyMini{margin-top:7px}.anatomyMini button{padding:5px 8px;font-size:11px}@media(max-width:800px){.anatomyLayout{grid-template-columns:1fr}.bodyGrid{grid-template-columns:1fr 1fr}.human{min-height:340px}.anatHideMobile{display:none}}@media(max-width:520px){.bodyGrid{grid-template-columns:1fr}.human{min-height:420px}}
`;

const ANAT_JS=`
let ANAT=null,ANATLIB=null,anatMuscles=new Set(JSON.parse(localStorage.getItem('dback_anat_muscles')||'[]')),anatJoints=new Set(JSON.parse(localStorage.getItem('dback_anat_joints')||'[]')),anatMode=localStorage.getItem('dback_anat_mode')||'compound',anatGoal=localStorage.getItem('dback_anat_goal')||'hypertrophy',anatResults=[];
function anatById(id){return ANAT&&ANAT.muscles.find(x=>x.id===id)}
function anatJointById(id){return ANAT&&ANAT.joints.find(x=>x.id===id)}
function anatomyBadges(e){const p=e&&e.anatomy;if(!p)return'';return '<div class=anatomyMini><span class=muted>Muscles</span> '+(p.primary||[]).slice(0,4).map(x=>'<span class="anatTag primary">'+esc((anatById(x)||{name:x}).name)+'</span>').join('')+(p.secondary||[]).slice(0,3).map(x=>'<span class="anatTag secondary">'+esc((anatById(x)||{name:x}).name)+'</span>').join('')+'<span class="anatTag">'+esc(p.pattern)+'</span><span class="anatTag">'+esc(p.mechanic)+'</span></div>'}
function decorateWorkoutAnatomy(){if(!W)return;const cards=$('view-workout').querySelectorAll('.exercise');cards.forEach((card,i)=>{const e=W.exercises&&W.exercises[i];if(!e||!e.anatomy||card.querySelector('.anatomyMini'))return;const left=card.querySelector('.between>div');if(left)left.insertAdjacentHTML('beforeend',anatomyBadges(e));const row=card.querySelector('.between>.row');if(row){const b=document.createElement('button');b.className='btn ghost';b.textContent='Anatomy';b.onclick=()=>openExerciseAnatomy(e);row.appendChild(b)}});const warms=$('view-workout').querySelectorAll('.warmitem');warms.forEach((card,i)=>{const e=W.warmup&&W.warmup[i];if(!e||!e.anatomy||card.querySelector('.anatomyMini'))return;card.insertAdjacentHTML('beforeend',anatomyBadges(e))})}
function decoratePlanAnatomy(d){const cards=$('view-plan').querySelectorAll('.exercise');cards.forEach((card,i)=>{const e=d&&d.exercises&&d.exercises[i];if(!e||!e.anatomy||card.querySelector('.anatomyMini'))return;const left=card.querySelector('.between>div');if(left)left.insertAdjacentHTML('beforeend',anatomyBadges(e));const row=card.querySelector('.between>.row');if(row){const b=document.createElement('button');b.className='btn ghost';b.textContent='Anatomy';b.onclick=()=>openExerciseAnatomy(e);row.appendChild(b)}})}
async function openExerciseAnatomy(e){await loadAnatomy();anatMuscles=new Set([...(e.anatomy.primary||[]),...(e.anatomy.secondary||[])]);anatJoints=new Set(e.anatomy.joints||[]);localStorage.setItem('dback_anat_muscles',JSON.stringify([...anatMuscles]));localStorage.setItem('dback_anat_joints',JSON.stringify([...anatJoints]));show('anatomy');renderAnatomy();const box=$('anatDetails');if(box)box.innerHTML=exerciseAnatomyDetail(e);setTimeout(()=>box&&box.scrollIntoView({behavior:'smooth',block:'center'}),50)}
function exerciseAnatomyDetail(e){const p=e.anatomy||{};const names=a=>(a||[]).map(x=>esc((anatById(x)||{name:x}).name)).join(', ')||'—';const joints=(p.joints||[]).map(x=>esc((anatJointById(x)||{name:x}).name)).join(', ')||'—';return '<h3>'+esc(e.name)+'</h3><div class=grid2><div><div class=muted>Primary</div><b>'+names(p.primary)+'</b></div><div><div class=muted>Secondary</div><b>'+names(p.secondary)+'</b></div><div><div class=muted>Stabilizers</div><b>'+names(p.stabilizers)+'</b></div><div><div class=muted>Joints</div><b>'+joints+'</b></div><div><div class=muted>Movement pattern</div><b>'+esc(p.pattern)+'</b></div><div><div class=muted>Plane / mechanic</div><b>'+esc(p.plane)+' · '+esc(p.mechanic)+'</b></div></div>'}
function bodySvg(view){const mp=ANAT.maps[view],outline='<circle class=bodyOutline cx=100 cy=26 r=16/><rect class=bodyOutline x=72 y=49 width=56 height=120 rx=24/><rect class=bodyOutline x=45 y=69 width=14 height=112 rx=7 transform="rotate(7 52 69)"/><rect class=bodyOutline x=141 y=69 width=14 height=112 rx=7 transform="rotate(-7 148 69)"/><rect class=bodyOutline x=70 y=166 width=25 height=169 rx=12/><rect class=bodyOutline x=105 y=166 width=25 height=169 rx=12/><ellipse class=bodyOutline cx=76 cy=347 rx=20 ry=8/><ellipse class=bodyOutline cx=124 cy=347 rx=20 ry=8/>';const muscles=mp.muscles.map(x=>'<ellipse class="muscleHotspot '+(anatMuscles.has(x[0])?'selected':'')+'" data-muscle="'+x[0]+'" cx="'+x[1]+'" cy="'+x[2]+'" rx="'+x[3]+'" ry="'+x[4]+'"><title>'+esc((anatById(x[0])||{}).name||x[0])+'</title></ellipse>').join('');const joints=mp.joints.map(x=>'<circle class="jointHotspot '+(anatJoints.has(x[0])?'selected':'')+'" data-joint="'+x[0]+'" cx="'+x[1]+'" cy="'+x[2]+'" r="4"><title>'+esc((anatJointById(x[0])||{}).name||x[0])+'</title></circle>').join('');return '<svg class=human viewBox="0 0 200 360" role=img aria-label="'+view+' body muscle map">'+outline+muscles+joints+'</svg>'}
function selectionSummary(){const ms=[...anatMuscles].map(anatById).filter(Boolean),js=[...anatJoints].map(anatJointById).filter(Boolean);return '<div class=card><div class=between><div><h3>Selected Targets</h3><div class=muted>'+ms.length+' muscle groups · '+js.length+' joints</div></div><button class="btn ghost" id=anatClear>Clear</button></div><div class=anatChips>'+ms.map(m=>'<button class="anatChip selected" data-muscle="'+m.id+'">'+esc(m.name)+'</button>').join('')+js.map(j=>'<button class="anatChip anatJoint selected" data-joint="'+j.id+'">'+esc(j.name)+'</button>').join('')+'</div></div>'}
function structureList(){return '<div class=card><h3>Muscle & Joint Index</h3><input id=anatSearch placeholder="Search muscles, sub-muscles, actions or joints"><div class=structureList id=anatStructureList>'+structureRows('')+'</div></div>'}
function structureRows(q){q=String(q||'').toLowerCase();const m=(ANAT.muscles||[]).filter(x=>!q||x.name.toLowerCase().includes(q)||x.region.toLowerCase().includes(q)||(x.parts||[]).some(p=>p.toLowerCase().includes(q))||(x.actions||[]).some(a=>a.toLowerCase().includes(q))).map(x=>'<div class=structureRow><div class=between><div><b>'+esc(x.name)+'</b><div class=muted>'+esc(x.region)+' · '+esc((x.parts||[]).join(', '))+'</div></div><button class="anatChip '+(anatMuscles.has(x.id)?'selected':'')+'" data-muscle="'+x.id+'">'+(anatMuscles.has(x.id)?'Selected':'Select')+'</button></div></div>').join('');const j=(ANAT.joints||[]).filter(x=>!q||x.name.toLowerCase().includes(q)||x.region.toLowerCase().includes(q)||(x.motions||[]).some(a=>a.toLowerCase().includes(q))).map(x=>'<div class=structureRow><div class=between><div><b>'+esc(x.name)+'</b><div class=muted>'+esc(x.region)+' · '+esc((x.motions||[]).join(', '))+'</div></div><button class="anatChip anatJoint '+(anatJoints.has(x.id)?'selected':'')+'" data-joint="'+x.id+'">'+(anatJoints.has(x.id)?'Selected':'Select')+'</button></div></div>').join('');return m+j}
function resultHtml(x){const p=x.anatomy||{};return '<div class=anatResult><div class=between><div><b>'+esc(x.name)+'</b><div class=muted>'+esc(p.pattern)+' · '+esc(p.plane)+' · '+esc(p.mechanic)+' · compound score '+esc(p.compoundScore)+'/10</div></div><span class=score>'+esc(x.coveragePct)+'% target coverage</span></div>'+anatomyBadges(x)+'<div class=row style="margin-top:8px"><button class="btn ghost" data-anatvideo="'+esc(x.video)+'" data-anatname="'+esc(x.name)+'">Video</button><button class="btn ghost" data-anatdetail="'+esc(x.name)+'">Biomechanics</button></div></div>'}
async function anatRecommend(){if(!anatMuscles.size&&!anatJoints.size){toast('Select at least one muscle or joint');return}try{const z=await api('/api/anatomy/recommend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({muscles:[...anatMuscles],joints:[...anatJoints],mode:anatMode,goal:anatGoal})});anatResults=z.results||[];renderAnatResults()}catch(e){toast(e.message)}}
function renderAnatResults(){const r=$('anatResults');if(!r)return;r.innerHTML=anatResults.length?anatResults.map(resultHtml).join(''):'<p class=muted>Select targets and press Recommend Exercises.</p>';r.querySelectorAll('[data-anatvideo]').forEach(b=>b.onclick=()=>openVideo(b.dataset.anatname,b.dataset.anatvideo,'Anatomy recommendation'));r.querySelectorAll('[data-anatdetail]').forEach(b=>{b.onclick=()=>{const e=anatResults.find(x=>x.name===b.dataset.anatdetail);$('anatDetails').innerHTML=exerciseAnatomyDetail(e);$('anatDetails').scrollIntoView({behavior:'smooth',block:'center'})}})}
function bindAnatomy(){document.querySelectorAll('[data-muscle]').forEach(b=>b.onclick=()=>{const id=b.dataset.muscle;if(anatMuscles.has(id))anatMuscles.delete(id);else anatMuscles.add(id);localStorage.setItem('dback_anat_muscles',JSON.stringify([...anatMuscles]));renderAnatomy()});document.querySelectorAll('[data-joint]').forEach(b=>b.onclick=()=>{const id=b.dataset.joint;if(anatJoints.has(id))anatJoints.delete(id);else anatJoints.add(id);localStorage.setItem('dback_anat_joints',JSON.stringify([...anatJoints]));renderAnatomy()});const c=$('anatClear');if(c)c.onclick=()=>{anatMuscles.clear();anatJoints.clear();localStorage.removeItem('dback_anat_muscles');localStorage.removeItem('dback_anat_joints');anatResults=[];renderAnatomy()};const s=$('anatSearch');if(s)s.oninput=()=>{$('anatStructureList').innerHTML=structureRows(s.value);bindAnatomy()};const rec=$('anatRecommend');if(rec)rec.onclick=anatRecommend;const mode=$('anatMode');if(mode)mode.onchange=()=>{anatMode=mode.value;localStorage.setItem('dback_anat_mode',anatMode)};const goal=$('anatGoal');if(goal)goal.onchange=()=>{anatGoal=goal.value;localStorage.setItem('dback_anat_goal',anatGoal)};renderAnatResults()}
function renderAnatomy(){if(!ANAT)return;$('view-anatomy').innerHTML='<div class="hero anatHero"><div class=muted>Scientific Training Anatomy · DBACK v6</div><h1>Anatomy & Biomechanics Lab</h1><p>Select one muscle, multiple muscles, or joints. The engine ranks exercises by primary, secondary and stabilizing roles, joint involvement, movement pattern, plane of motion and multi-joint coverage.</p><div class=row><select id=anatMode style="width:auto"><option value=compound '+(anatMode==='compound'?'selected':'')+'>Prioritize compound</option><option value=any '+(anatMode==='any'?'selected':'')+'>Any exercise</option><option value=isolation '+(anatMode==='isolation'?'selected':'')+'>Isolation focus</option></select><select id=anatGoal style="width:auto"><option value=hypertrophy '+(anatGoal==='hypertrophy'?'selected':'')+'>Hypertrophy</option><option value=strength '+(anatGoal==='strength'?'selected':'')+'>Strength</option><option value=mobility '+(anatGoal==='mobility'?'selected':'')+'>Mobility</option><option value=conditioning '+(anatGoal==='conditioning'?'selected':'')+'>Conditioning</option></select><button class="btn green" id=anatRecommend>Recommend Exercises</button></div></div>'+selectionSummary()+'<div class=anatomyLayout><div><div class=card><div class=between><div><h3>Interactive Body Map</h3><div class=muted>Red = selected muscle · green joint = selected joint</div></div></div><div class=bodyGrid><div class=bodyPanel><b>Front</b>'+bodySvg('front')+'</div><div class=bodyPanel><b>Back</b>'+bodySvg('back')+'</div></div></div><div class=card><h3>Best Exercise Matches</h3><div id=anatResults><p class=muted>Select targets and press Recommend Exercises.</p></div></div></div><div>'+structureList()+'<div class=card id=anatDetails><h3>Biomechanics Detail</h3><p class=muted>Open Anatomy from any exercise or choose Biomechanics from a recommendation.</p></div><div class=scienceBox><b>Scientific interpretation</b><p class=muted>'+esc(ANAT.scienceNote)+'</p><div>'+ANAT.references.map(x=>'<a class="anatTag" target=_blank rel=noopener href="'+esc(x.url)+'">'+esc(x.title)+'</a>').join('')+'</div></div></div></div>';bindAnatomy()}
async function loadAnatomy(){try{ANAT=ANAT||await api('/api/anatomy');ANATLIB=ANATLIB||await api('/api/library');renderAnatomy()}catch(e){toast(e.message)}}
`;

function patchHtml(html){let out=html;
 out=out.replaceAll('v5.0.0','v6.0.0');
 out=out.replace('Fitness OS · v6.0.0 · Natural Human Coach','Fitness OS · v6.0.0 · Anatomy Intelligence · Natural Human Coach');
 out=out.replace('</style></head>',ANAT_CSS+'</style></head>');
 out=out.replace('<section class=view id=view-profile></section>','<section class=view id=view-anatomy></section><section class=view id=view-profile></section>');
 out=out.replace("const VIEWS=[['home','Home'],['workout','Workout'],['plan','Full Plan'],['progress','Progress'],['history','History'],['coach','AI Coach'],['profile','Profile']];","const VIEWS=[['home','Home'],['workout','Workout'],['plan','Full Plan'],['anatomy','Anatomy Lab'],['progress','Progress'],['history','History'],['coach','AI Coach'],['profile','Profile']];");
 out=out.replace("if(v==='profile')loadProfile();if(v==='coach')renderCoach()","if(v==='profile')loadProfile();if(v==='anatomy')loadAnatomy();if(v==='coach')renderCoach()");
 out=out.replace('async function loadAll(){',ANAT_JS+'\nasync function loadAll(){');
 out=out.replace("document.querySelectorAll('[data-videoedit]').forEach(b=>b.onclick=()=>openVideoEdit(b.dataset.videoedit,b.dataset.videourl));startTimers()}","document.querySelectorAll('[data-videoedit]').forEach(b=>b.onclick=()=>openVideoEdit(b.dataset.videoedit,b.dataset.videourl));decorateWorkoutAnatomy();startTimers()}");
 out=out.replace("document.querySelectorAll('[data-pedit]').forEach(b=>b.onclick=()=>openVideoEdit(b.dataset.pedit,b.dataset.url))}","document.querySelectorAll('[data-pedit]').forEach(b=>b.onclick=()=>openVideoEdit(b.dataset.pedit,b.dataset.url));decoratePlanAnatomy(d)}");
 return out;
}

async function handleMcp(request,env,ctx,url){let q;try{q=await request.clone().json()}catch{return base.fetch(request,env,ctx)}
 if(q?.method==='tools/call'&&ANATOMY_MCP_TOOLS.some(t=>t.name===q.params?.name)){
  try{let data;if(q.params.name==='get_anatomy_atlas')data=atlas();else if(q.params.name==='get_exercise_anatomy'){const name=q.params.arguments?.exercise_name||'';data={type:'exercise_anatomy',exercise_name:name,anatomy:hydrateProfile(exerciseProfile(name)),version:VERSION}}else data=await recommendations(env,ctx,url.origin,q.params.arguments||{});return rpc(q.id,toolOutput(data,q.params.name==='recommend_exercises_for_muscles'?'Exercise recommendations based on selected muscles and joint mechanics.':'Scientific training anatomy data.'))}catch(e){return rpc(q.id,{isError:true,content:[{type:'text',text:e.message}]})}
 }
 const res=await base.fetch(request,env,ctx);if(!res.headers.get('content-type')?.includes('application/json'))return res;let data;try{data=JSON.parse(await res.text())}catch{return res}
 if(q?.method==='initialize'&&data?.result?.serverInfo){data.result.serverInfo.version=VERSION;data.result.instructions=(data.result.instructions||'')+' The app also provides a scientific training anatomy atlas, muscle/joint selection, biomechanics profiles, and muscle-targeted exercise recommendations.'}
 if(q?.method==='tools/list'&&data?.result?.tools){const have=new Set(data.result.tools.map(x=>x.name));for(const t of ANATOMY_MCP_TOOLS)if(!have.has(t.name))data.result.tools.push(t)}
 return jsonResponse(data,res.status,{'mcp-protocol-version':res.headers.get('mcp-protocol-version')||'2025-06-18'});
}

export default{async fetch(request,env,ctx){const url=new URL(request.url),path=url.pathname;
 if(request.method==='OPTIONS')return base.fetch(request,env,ctx);
 if(path==='/api/anatomy'&&request.method==='GET')return jsonResponse(atlas());
 if(path==='/api/anatomy/exercise'&&request.method==='GET'){const name=url.searchParams.get('name')||'';return jsonResponse({type:'exercise_anatomy',exercise_name:name,anatomy:hydrateProfile(exerciseProfile(name)),version:VERSION})}
 if(path==='/api/anatomy/recommend'&&request.method==='POST'){try{return jsonResponse(await recommendations(env,ctx,url.origin,await request.json()))}catch(e){return jsonResponse({error:e.message},400)}}
 if(path==='/mcp'&&request.method==='POST')return handleMcp(request,env,ctx,url);
 if(path==='/api/chat'&&request.method==='POST'){
  try{const body=await request.clone().json();const lib=enrichPayload(await baseJson(env,ctx,url.origin,'/api/library'),'/api/library');const message=anatomyContext(body.message||'',lib);const headers=new Headers(request.headers);headers.set('content-type','application/json');const r2=new Request(request.url,{method:'POST',headers,body:JSON.stringify({...body,message})});return base.fetch(r2,env,ctx)}catch{return base.fetch(request,env,ctx)}
 }
 const res=await base.fetch(request,env,ctx);
 if(path==='/'&&request.method==='GET'&&res.headers.get('content-type')?.includes('text/html')){const text=await res.text();const headers=new Headers(res.headers);headers.set('cache-control','no-store, no-cache, must-revalidate');return new Response(patchHtml(text),{status:res.status,headers})}
 if(['/api/today','/api/plan','/api/library','/health'].includes(path)&&res.headers.get('content-type')?.includes('application/json')){try{return jsonResponse(enrichPayload(JSON.parse(await res.text()),path),res.status)}catch{return res}}
 return res;
}};
