const UI='ui://dback/coach.html',Y='https://www.youtube.com/watch?v=',TZ='America/New_York';
let DB,PROGRAM;
const day=()=>new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'long'}).format(new Date());
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const isAllowedOrigin=o=>{if(!o)return true;try{const h=new URL(o).hostname;return h==='chatgpt.com'||h==='chat.openai.com'||h==='platform.openai.com'||h.endsWith('.openai.com');}catch{return false;}};
const baseHeaders=()=>({'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type,accept,mcp-session-id,mcp-protocol-version,last-event-id,authorization','access-control-expose-headers':'mcp-session-id,mcp-protocol-version','cache-control':'no-store','vary':'Origin, Accept'});
async function program(){if(PROGRAM)return PROGRAM;const r=await DB.prepare("SELECT value FROM app_config WHERE key='program'").first();if(!r?.value)throw Error('Workout program is not initialized');return PROGRAM=JSON.parse(r.value)}
async function workout(d=day()){const all=await program(),p=all[d]||all.Monday,x=[];for(const a of p.slice(1)){const id=slug(a[0]),s=await DB.prepare('SELECT * FROM exercise_state WHERE exercise_id=?').bind(id).first();x.push({id,name:a[0],sets:a[1],reps:a[2],rest:a[3],rir:a[4],video:Y+a[5],state:s||null})}const active=await DB.prepare("SELECT * FROM workout_sessions WHERE status='active' ORDER BY started_at DESC LIMIT 1").first();return{type:'workout',day:d,focus:p[0],targetMinutes:60,warmupCount:15,exercises:x,activeSession:active||null}}
async function start(a={}){const id=crypto.randomUUID(),d=a.day||day(),ts=new Date().toISOString();await DB.prepare('INSERT INTO workout_sessions(id,workout_date,day_name,started_at,readiness,sleep_hours,bodyweight_lb,status) VALUES(?,?,?,?,?,?,?,?)').bind(id,ts.slice(0,10),d,ts,a.readiness??null,a.sleep_hours??null,a.bodyweight_lb??null,'active').run();return{...await workout(d),activeSession:{id,day_name:d,started_at:ts,status:'active'}}}
async function log(a){const ts=new Date().toISOString();await DB.prepare('INSERT INTO set_logs(session_id,exercise_id,set_number,weight_lb,reps,seconds,rir,rpe,discomfort,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(a.session_id,a.exercise_id,a.set_number,a.weight_lb??null,a.reps??null,a.seconds??null,a.rir??null,a.rpe??null,a.discomfort??0,ts).run();const p=await DB.prepare('SELECT * FROM exercise_state WHERE exercise_id=?').bind(a.exercise_id).first(),w=a.weight_lb??p?.last_weight_lb??null,r=a.reps??p?.last_reps??null,nw=w;if(w!=null&&r!=null&&(a.rir==null||a.rir>=1))nw=Math.round((w+2.5)*2)/2;await DB.prepare(`INSERT INTO exercise_state(exercise_id,last_weight_lb,last_reps,last_seconds,last_rir,best_weight_lb,best_reps,best_seconds,next_weight_lb,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(exercise_id) DO UPDATE SET last_weight_lb=excluded.last_weight_lb,last_reps=excluded.last_reps,last_seconds=excluded.last_seconds,last_rir=excluded.last_rir,best_weight_lb=MAX(COALESCE(exercise_state.best_weight_lb,0),COALESCE(excluded.last_weight_lb,0)),best_reps=MAX(COALESCE(exercise_state.best_reps,0),COALESCE(excluded.last_reps,0)),best_seconds=MAX(COALESCE(exercise_state.best_seconds,0),COALESCE(excluded.last_seconds,0)),next_weight_lb=excluded.next_weight_lb,updated_at=excluded.updated_at`).bind(a.exercise_id,w,r,a.seconds??null,a.rir??null,w,r,a.seconds??null,nw,ts).run();return{type:'set_logged',recommendation:nw>w?`Next session target: ${nw} lb if form stays clean.`:'Keep current load and progress reps/time.'}}
async function finish(a){const x=await DB.prepare('SELECT * FROM workout_sessions WHERE id=?').bind(a.session_id).first();if(!x)throw Error('Workout session not found');const end=new Date().toISOString(),dur=Math.max(0,Math.floor((Date.parse(end)-Date.parse(x.started_at))/1000));await DB.prepare("UPDATE workout_sessions SET completed_at=?,duration_seconds=?,session_rpe=?,notes=?,status='complete' WHERE id=?").bind(end,dur,a.session_rpe??null,a.notes??null,a.session_id).run();const s=await DB.prepare('SELECT COUNT(*) count,SUM(COALESCE(weight_lb,0)*COALESCE(reps,0)) volume FROM set_logs WHERE session_id=?').bind(a.session_id).first();return{type:'summary',duration_seconds:dur,sets:+(s?.count||0),volume_lb_reps:+(s?.volume||0)}}
const defs=[
['open_coach','Open DBACK AI Coach','Use this when the user wants to open the interactive DBACK AI workout coach.',{}],
['get_today_workout','Get today workout','Use this when the user asks what to train today.',{day:{type:'string'}}],
['start_workout','Start tracked workout','Use this when the user is ready to begin a tracked workout.',{day:{type:'string'},readiness:{type:'integer',minimum:1,maximum:10},sleep_hours:{type:'number'},bodyweight_lb:{type:'number'}}],
['log_set','Log completed set','Use this when the user completes a set and wants it recorded.',{session_id:{type:'string'},exercise_id:{type:'string'},set_number:{type:'integer',minimum:1},weight_lb:{type:'number'},reps:{type:'integer'},seconds:{type:'integer'},rir:{type:'number'},rpe:{type:'number'},discomfort:{type:'integer'}}],
['complete_workout','Complete workout','Use this when the user finishes a workout.',{session_id:{type:'string'},session_rpe:{type:'number'},notes:{type:'string'}}],
['get_history','Get workout history','Use this when the user asks for recent workout history.',{limit:{type:'integer',minimum:1,maximum:30}}]
];
const tools=defs.map(x=>({name:x[0],title:x[1],description:x[2],inputSchema:{type:'object',properties:x[3],required:x[0]==='log_set'?['session_id','exercise_id','set_number']:x[0]==='complete_workout'?['session_id']:[]},annotations:{readOnlyHint:['open_coach','get_today_workout','get_history'].includes(x[0]),destructiveHint:false,openWorldHint:false},_meta:{'openai/outputTemplate':UI}}));
const out=(x,t='DBACK AI Coach updated.')=>({structuredContent:x,content:[{type:'text',text:t}]});
async function call(n,a={}){if(n==='open_coach'||n==='get_today_workout')return out(await workout(a.day||day()));if(n==='start_workout')return out(await start(a),'Workout started.');if(n==='log_set')return out(await log(a),'Set logged.');if(n==='complete_workout')return out(await finish(a),'Workout complete.');if(n==='get_history')return out({type:'history',sessions:(await DB.prepare('SELECT * FROM workout_sessions ORDER BY started_at DESC LIMIT ?').bind(Math.min(a.limit||10,30)).all()).results||[]});throw Error('Unknown tool')}
function html(){return`<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><style>body{margin:0;background:#0b1220;color:#f8fafc;font:14px -apple-system,Segoe UI,sans-serif}.a{max-width:820px;margin:auto;padding:16px}.h,.c{background:#111827;border:1px solid #263247;border-radius:15px;padding:14px;margin:10px 0}.h{background:#172554}.m{color:#94a3b8;font-size:12px}h1,h3{margin:5px 0}.g{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:9px 0}input,button,a{border:0;border-radius:9px;padding:9px;font-weight:700}input{width:100%;box-sizing:border-box;background:#0f172a;color:white;border:1px solid #334155}button,a{background:white;color:#111827;text-decoration:none}.r{display:flex;gap:7px;flex-wrap:wrap}@media(max-width:600px){.g{grid-template-columns:repeat(2,1fr)}}</style><div class=a><b>DBACK AI COACH</b><div id=r></div></div><script>let d=window.openai?.toolOutput?.structuredContent||{},s=d.activeSession;async function C(n,a){let z=await window.openai.callTool(n,a||{}),x=z?.structuredContent||z;if(x){d=x;s=x.activeSession||s;R()}return x}async function S(){s=(await C('start_workout',{day:d.day,readiness:8})).activeSession}async function L(id,i){if(!s?.id)await S();let q=k=>document.getElementById(k+i).value,a={session_id:s.id,exercise_id:id,set_number:+q('s')||1};if(q('w'))a.weight_lb=+q('w');if(q('p'))a.reps=+q('p');if(q('i'))a.rir=+q('i');await C('log_set',a)}async function F(){if(s?.id)await C('complete_workout',{session_id:s.id,session_rpe:8})}function R(){let r=document.getElementById('r');if(d.type=='summary'){r.innerHTML='<div class=h><h1>Workout Complete</h1><div class=m>'+Math.round(d.duration_seconds/60)+' min · '+d.sets+' sets · '+Math.round(d.volume_lb_reps||0)+' lb-reps</div></div>';return}r.innerHTML='<div class=h><div class=m>'+d.day+'</div><h1>'+d.focus+'</h1><div class=m>60 min · '+(s?.id?'tracking active':'ready')+' · '+(d.warmupCount||15)+' warm-up movements</div><div class=r style="margin-top:10px"><button onclick=S()>Start</button><button onclick=F()>Finish</button></div></div>'+(d.exercises||[]).map((e,i)=>'<div class=c><div class=m>'+e.sets+' × '+e.reps+' · rest '+e.rest+'s · RIR '+e.rir+'</div><h3>'+e.name+'</h3><div class=m>Previous '+(e.state?.last_weight_lb??'—')+' lb × '+(e.state?.last_reps??'—')+' · next '+(e.state?.next_weight_lb??'—')+'</div><div class=g><input id=s'+i+' value=1 type=number><input id=w'+i+' placeholder=lb type=number step=2.5><input id=p'+i+' placeholder=reps type=number><input id=i'+i+' placeholder=RIR type=number></div><div class=r><button onclick="L(\''+e.id+'\','+i+')">Complete Set</button><a target=_blank href="'+e.video+'">Instruction Video</a></div></div>').join('')}R()</script>`}
const rpc=(id,result,status=200)=>new Response(JSON.stringify({jsonrpc:'2.0',id,result}),{status,headers:{...baseHeaders(),'content-type':'application/json','mcp-protocol-version':'2025-06-18'}});
const err=(id,code,message,status=400)=>new Response(JSON.stringify({jsonrpc:'2.0',id:id??null,error:{code,message}}),{status,headers:{...baseHeaders(),'content-type':'application/json'}});
async function mcp(r){
  const ct=(r.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();
  if(ct!=='application/json')return new Response('Unsupported Media Type',{status:415,headers:baseHeaders()});
  let q;try{q=await r.json()}catch{return err(null,-32700,'Parse error',400)}
  if(!q||q.jsonrpc!=='2.0'||typeof q.method!=='string')return err(q?.id??null,-32600,'Invalid Request',400);
  const {id,method,params}=q;
  if(method==='initialize'){
    const requested=params?.protocolVersion;
    const supported=['2025-11-25','2025-06-18','2025-03-26'];
    const protocolVersion=supported.includes(requested)?requested:'2025-06-18';
    return rpc(id,{protocolVersion,capabilities:{tools:{listChanged:false},resources:{subscribe:false,listChanged:false}},serverInfo:{name:'DBACK AI Coach',version:'1.1.0'},instructions:'DBACK AI Coach tracks workouts, sets, load, reps, RIR/RPE, history, and progression. Use get_today_workout before starting if the user asks what to do today.'});
  }
  if(id==null){return new Response(null,{status:202,headers:baseHeaders()});}
  if(method==='ping')return rpc(id,{});
  if(method==='tools/list')return rpc(id,{tools});
  if(method==='prompts/list')return rpc(id,{prompts:[]});
  if(method==='resources/templates/list')return rpc(id,{resourceTemplates:[]});
  if(method==='resources/list')return rpc(id,{resources:[{uri:UI,name:'DBACK AI Coach',description:'Interactive workout coach interface',mimeType:'text/html;profile=mcp-app'}]});
  if(method==='resources/read'&&params?.uri===UI)return rpc(id,{contents:[{uri:UI,mimeType:'text/html;profile=mcp-app',text:html(),_meta:{'openai/widgetDescription':'Interactive DBACK workout coach with set logging, workout history, progression, and instructional videos.',ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:['https://www.youtube.com']}}}}]});
  if(method==='tools/call'){try{return rpc(id,await call(params?.name,params?.arguments||{}))}catch(e){return rpc(id,{isError:true,content:[{type:'text',text:e?.message||'Tool failed'}]})}}
  return err(id,-32601,'Method not found',404);
}
export default{async fetch(r,env){DB=env.DB;const u=new URL(r.url),origin=r.headers.get('origin');if(!isAllowedOrigin(origin))return new Response('Forbidden',{status:403,headers:baseHeaders()});if(r.method==='OPTIONS')return new Response(null,{status:204,headers:baseHeaders()});if(u.pathname==='/mcp'){
  if(r.method==='POST')return mcp(r);
  if(r.method==='GET')return new Response('DBACK AI Coach MCP endpoint is online. Connect with an MCP client using Streamable HTTP POST.',{status:405,headers:{...baseHeaders(),'content-type':'text/plain;charset=utf-8','allow':'POST, OPTIONS'}});
  if(r.method==='DELETE')return new Response(null,{status:405,headers:{...baseHeaders(),'allow':'POST, OPTIONS'}});
}
if(u.pathname==='/health')return Response.json({ok:true,service:'DBACK AI Coach',version:'1.1.0',database:!!env.DB,mcp:'/mcp'},{headers:baseHeaders()});if(u.pathname==='/')return new Response(html(),{headers:{...baseHeaders(),'content-type':'text/html;charset=utf-8'}});return new Response('Not found',{status:404,headers:baseHeaders()})}}
