import base from './worker-v8.js';
const VERSION='8.0.1';
const CSS=`
.bodyGrid{display:block!important;min-width:0!important;max-width:100%!important}.bodyPanel{display:none!important;min-width:0!important;max-width:100%!important}.bodyPanel.atlasActive{display:block!important}.atlasSeg{display:inline-flex!important}.atlasDesktopLabels{display:none!important}.atlasToolbar{position:sticky;top:0;z-index:20;background:rgba(7,17,31,.95);backdrop-filter:blur(12px);padding:7px 0}.anatomyLayout,.card,.hero,.main,.view,.bodyPanel,.realAnatomyMap{min-width:0!important;max-width:100%!important;box-sizing:border-box!important}.smartLabelRail{max-width:100%!important}.atlasSelectedCard{max-width:100%!important}.realAnatomyMap{width:min(100%,560px)!important;margin-left:auto!important;margin-right:auto!important}.mapLegend{display:none!important}.atlasCredit{display:none!important}.atlasHint{display:block!important}
@media(max-width:900px){.side,aside.side,.sidebar{display:none!important}.layout,.shell{display:block!important;width:100%!important;max-width:100%!important;grid-template-columns:1fr!important}.main{width:100%!important;max-width:100%!important;margin:0!important;padding-left:12px!important;padding-right:12px!important;overflow-x:hidden!important}.topbar{width:100%!important;max-width:100%!important;flex-wrap:wrap!important}.mobileNav{display:flex!important;width:100%!important;max-width:100%!important;overflow-x:auto!important}.anatomyLayout{grid-template-columns:minmax(0,1fr)!important}.atlasToolbar{width:100%!important}.atlasLabelControl{width:100%!important;justify-content:space-between!important}.atlasLabelControl select{flex:1!important;max-width:190px!important}.realAnatomyMap{max-height:66vh!important;aspect-ratio:4/5.6!important}}
`;
function patch(html){return html.replaceAll('v8.0.0',VERSION).replaceAll('8.0.0',VERSION).replaceAll('v7.0.2',VERSION).replaceAll('7.0.2',VERSION).replaceAll('v7.0.1',VERSION).replaceAll('7.0.1',VERSION).replace('</style>',CSS+'</style>')}
async function patchJson(r){const t=r.headers.get('content-type')||'';if(!t.includes('application/json'))return r;try{const d=await r.json();if(d&&typeof d==='object'&&'version' in d)d.version=VERSION;const h=new Headers(r.headers);h.set('cache-control','no-store');return new Response(JSON.stringify(d),{status:r.status,headers:h})}catch{return r}}
export default{async fetch(req,env,ctx){const u=new URL(req.url),r=await base.fetch(req,env,ctx);if(req.method==='GET'&&u.pathname==='/'){const t=r.headers.get('content-type')||'';if(t.includes('text/html')){const h=new Headers(r.headers);h.set('cache-control','no-store,no-cache,must-revalidate');return new Response(patch(await r.text()),{status:r.status,headers:h})}}if(req.method==='GET'&&(u.pathname==='/health'||u.pathname==='/api/anatomy'))return patchJson(r);return r}};
